const typographyStyles = [
  {
    id: "cinematic-bold",
    name: "Cinematic Bold",
    category: "cinematic",
    tags: ["bold", "uppercase", "cinematic", "blockbuster"],
    heading: { fontFamily: "Arial", fontSize: 82, fontWeight: 900, letterSpacing: 5, lineHeight: 0.95, uppercase: true },
    name: { fontFamily: "Arial", fontSize: 94, fontWeight: 900, letterSpacing: 2, lineHeight: 1, uppercase: true },
    details: { fontFamily: "Arial", fontSize: 31, fontWeight: 600, letterSpacing: 2, lineHeight: 1.2, uppercase: true },
    quote: { fontFamily: "Arial", fontSize: 27, fontWeight: 400, letterSpacing: 0, lineHeight: 1.35, uppercase: false },
  },
  {
    id: "editorial-serif",
    name: "Editorial Serif",
    category: "magazine",
    tags: ["serif", "editorial", "fashion", "vogue"],
    heading: { fontFamily: "Georgia", fontSize: 73, fontWeight: 700, letterSpacing: 1, lineHeight: 1, uppercase: true },
    name: { fontFamily: "Georgia", fontSize: 88, fontWeight: 700, letterSpacing: 0, lineHeight: 1, uppercase: false },
    details: { fontFamily: "Arial", fontSize: 29, fontWeight: 600, letterSpacing: 2, lineHeight: 1.25, uppercase: true },
    quote: { fontFamily: "Georgia", fontSize: 30, fontWeight: 400, letterSpacing: 0, lineHeight: 1.4, uppercase: false, italic: true },
  },
  {
    id: "modern-clean",
    name: "Modern Clean",
    category: "modern",
    tags: ["modern", "clean", "simple", "minimal"],
    heading: { fontFamily: "Arial", fontSize: 67, fontWeight: 700, letterSpacing: 7, lineHeight: 1, uppercase: true },
    name: { fontFamily: "Arial", fontSize: 86, fontWeight: 800, letterSpacing: -1, lineHeight: 1, uppercase: false },
    details: { fontFamily: "Arial", fontSize: 28, fontWeight: 500, letterSpacing: 1, lineHeight: 1.3, uppercase: false },
    quote: { fontFamily: "Arial", fontSize: 26, fontWeight: 400, letterSpacing: 0, lineHeight: 1.4, uppercase: false },
  },
  {
    id: "luxury-serif",
    name: "Luxury Serif",
    category: "luxury",
    tags: ["luxury", "elegant", "serif", "gold"],
    heading: { fontFamily: "Georgia", fontSize: 68, fontWeight: 700, letterSpacing: 6, lineHeight: 1, uppercase: true },
    name: { fontFamily: "Georgia", fontSize: 96, fontWeight: 700, letterSpacing: 1, lineHeight: 1, uppercase: false },
    details: { fontFamily: "Arial", fontSize: 29, fontWeight: 600, letterSpacing: 3, lineHeight: 1.25, uppercase: true },
    quote: { fontFamily: "Georgia", fontSize: 28, fontWeight: 400, letterSpacing: 0, lineHeight: 1.45, uppercase: false, italic: true },
  },
  {
    id: "neon-display",
    name: "Neon Display",
    category: "neon",
    tags: ["neon", "display", "future", "glow"],
    heading: { fontFamily: "Arial", fontSize: 72, fontWeight: 900, letterSpacing: 4, lineHeight: 1, uppercase: true },
    name: { fontFamily: "Arial", fontSize: 92, fontWeight: 900, letterSpacing: 0, lineHeight: 1, uppercase: true },
    details: { fontFamily: "Arial", fontSize: 29, fontWeight: 700, letterSpacing: 2, lineHeight: 1.25, uppercase: true },
    quote: { fontFamily: "Arial", fontSize: 26, fontWeight: 500, letterSpacing: 1, lineHeight: 1.35, uppercase: false },
  },
  {
    id: "soft-elegant",
    name: "Soft Elegant",
    category: "floral",
    tags: ["soft", "elegant", "feminine", "script"],
    heading: { fontFamily: "Georgia", fontSize: 64, fontWeight: 700, letterSpacing: 2, lineHeight: 1.05, uppercase: false },
    name: { fontFamily: "Georgia", fontSize: 84, fontWeight: 700, letterSpacing: 0, lineHeight: 1, uppercase: false, italic: true },
    details: { fontFamily: "Arial", fontSize: 28, fontWeight: 500, letterSpacing: 1, lineHeight: 1.3, uppercase: false },
    quote: { fontFamily: "Georgia", fontSize: 29, fontWeight: 400, letterSpacing: 0, lineHeight: 1.4, uppercase: false, italic: true },
  },
  {
    id: "athletic-block",
    name: "Athletic Block",
    category: "sports",
    tags: ["sports", "block", "heavy", "athlete", "champions"],
    heading: { fontFamily: "Impact, Arial Black, Arial", fontSize: 78, fontWeight: 900, letterSpacing: 3, lineHeight: 0.9, uppercase: true },
    name: { fontFamily: "Impact, Arial Black, Arial", fontSize: 98, fontWeight: 900, letterSpacing: 2, lineHeight: 0.95, uppercase: true },
    details: { fontFamily: "Arial", fontSize: 30, fontWeight: 700, letterSpacing: 3, lineHeight: 1.2, uppercase: true },
    quote: { fontFamily: "Arial", fontSize: 27, fontWeight: 600, letterSpacing: 1, lineHeight: 1.35, uppercase: false },
  },
  {
    id: "college-varsity",
    name: "College Varsity",
    category: "college",
    tags: ["college", "varsity", "academic", "graduate", "class"],
    heading: { fontFamily: "Georgia, Arial", fontSize: 70, fontWeight: 800, letterSpacing: 4, lineHeight: 1, uppercase: true },
    name: { fontFamily: "Georgia, Arial", fontSize: 90, fontWeight: 800, letterSpacing: 1, lineHeight: 1, uppercase: true },
    details: { fontFamily: "Arial", fontSize: 32, fontWeight: 700, letterSpacing: 2, lineHeight: 1.25, uppercase: true },
    quote: { fontFamily: "Georgia, Arial", fontSize: 28, fontWeight: 400, letterSpacing: 0, lineHeight: 1.4, uppercase: false, italic: true },
  },
  {
    id: "vintage-grotesk",
    name: "Vintage Grotesk",
    category: "creative",
    tags: ["vintage", "grotesk", "retro", "warm", "classic"],
    heading: { fontFamily: "Arial", fontSize: 66, fontWeight: 800, letterSpacing: 5, lineHeight: 1.05, uppercase: true },
    name: { fontFamily: "Georgia", fontSize: 88, fontWeight: 700, letterSpacing: 1, lineHeight: 1.05, uppercase: false },
    details: { fontFamily: "Arial", fontSize: 28, fontWeight: 600, letterSpacing: 2, lineHeight: 1.25, uppercase: true },
    quote: { fontFamily: "Georgia", fontSize: 27, fontWeight: 400, letterSpacing: 0, lineHeight: 1.4, uppercase: false },
  },
  {
    id: "futuristic-tech",
    name: "Futuristic Tech",
    category: "futuristic",
    tags: ["future", "tech", "cyber", "terminal", "mono"],
    heading: { fontFamily: "Courier New, monospace, Arial", fontSize: 68, fontWeight: 800, letterSpacing: 6, lineHeight: 1, uppercase: true },
    name: { fontFamily: "Arial", fontSize: 90, fontWeight: 900, letterSpacing: 4, lineHeight: 1, uppercase: true },
    details: { fontFamily: "Courier New, monospace, Arial", fontSize: 27, fontWeight: 700, letterSpacing: 3, lineHeight: 1.3, uppercase: true },
    quote: { fontFamily: "Arial", fontSize: 25, fontWeight: 400, letterSpacing: 1, lineHeight: 1.4, uppercase: false },
  },
];

module.exports = typographyStyles;
